<?xml version="1.0" encoding="utf-8"?>
<!--xacro file to define a simple 4 wheel differential drive (skid steer) robot-->

<robot name="skid_steer_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--body dimension-->
<xacro:property name="base_link_x_dim" value="1" />
<xacro:property name="base_link_y_dim" value="0.6" />
<xacro:property name="base_link_z_dim" value="0.3" />

<!--wheel dimensions-->
<xacro:property name="wheel_link_radius" value="0.15" />
<xacro:property name="wheel_link_length" value="0.1" />
<xacro:property name="wheel_link_z_location" value="-0.1" />

<!--material density-->
<xacro:property name="body_density" value="2710.0" />
<xacro:property name="wheel_density" value="2710.0" />

<!--pi constant-->
<xacro:property name="pi_const" value="3.14159265" />

<!--robot body and wheel mass-->
<xacro:property name="body_mass"
 value="${body_density*base_link_x_dim*base_link_y_dim*base_link_z_dim}" />

<xacro:property name="wheel_mass"
 value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}" />

<!--moments of inertia of wheel-->
<xacro:property name="Iz_wheel"
 value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}" />

<xacro:property name="I_wheel"
 value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}" />

<!--macro defines complete inertial section of the wheel-->
<xacro:macro name="inertial_wheel">
    <inertial>
    <origin rpy="0 0 0" xyz="0 0 0" />
    <mass value="${wheel_mass}"/>
    <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0.0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>

<!--including .gazebo file-->
<xacro:include filename="$(find diff_drive_bot)/model/robot.gazebo" />

<!--defining dummy link for gazebo
<link name="dummy" />
<joint name="dummy_joint" type="fixed">
    <parent link="dummy" />
    <child link="base_link" />
</joint>-->

<!--base link-->
<link name="base_link">
    <visual>
        <geometry>
            <box size="${base_link_x_dim} ${base_link_y_dim} ${base_link_z_dim}" />
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0" />
    </visual>
    <collision>
        <geometry>
            <box size="${base_link_x_dim} ${base_link_y_dim} ${base_link_z_dim}" />
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0" />
    </collision>
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <mass value="${body_mass}" />
        <inertia
        ixx="${(1/12)*body_mass*(base_link_y_dim*base_link_y_dim+base_link_z_dim*base_link_z_dim)}"
        ixy="0" ixz="0" iyy="${(1/12)*body_mass*(base_link_x_dim*base_link_x_dim+base_link_z_dim*base_link_z_dim)}"
        iyz="0"
        izz="${(1/12)*body_mass*(base_link_y_dim*base_link_y_dim+base_link_x_dim*base_link_x_dim)}" />
    </inertial>
</link>

<!--end of base link-->

<!--defining back right wheel-->
<joint name="back_rw_joint" type="continuous">
    <parent link="base_link" />
    <child link="back_rw_link" />
    <origin xyz="${-base_link_x_dim/2+1.2*wheel_link_radius} ${-base_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000" />
    <dynamics damping="1.0" friction="1.0" />
</joint>

<link name="back_rw_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </visual>
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </collision>
    <xacro:inertial_wheel />
</link>


<!--deifining back left wheel-->
<joint name="back_lw_joint" type="continuous">
    <parent link="base_link" />
    <child link="back_lw_link" />
    <origin xyz="${-base_link_x_dim/2+1.2*wheel_link_radius} ${base_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="1000" velocity="1000" />
    <dynamics damping="1.0" friction="1.0" />
</joint>

<link name="back_lw_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </visual>
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </collision>
    <xacro:inertial_wheel />
</link>


<!--defining front right wheel-->
<joint name="front_rw_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_rw_link" />
    <origin xyz="${base_link_x_dim/2-1.2*wheel_link_radius} ${-base_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000" />
    <dynamics damping="1.0" friction="1.0" />
</joint>

<link name="front_rw_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </visual>
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </collision>
    <xacro:inertial_wheel />
</link>


<!--defining front left wheel-->
<joint name="front_lw_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_lw_link" />
    <origin xyz="${base_link_x_dim/2-1.2*wheel_link_radius} ${base_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000" />
    <dynamics damping="1.0" friction="1.0" />
</joint>

<link name="front_lw_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </visual>
    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
        </geometry>
    </collision>
    <xacro:inertial_wheel />
</link>
</robot>


